import Otter_api
import time


otter = Otter_api.otter()

otter.controller_inputs_torque(0, 0)
time.sleep(1)
otter.controller_inputs_torque(20, 0)
time.sleep(1)
otter.controller_inputs_torque(40, 0)
time.sleep(1)
otter.controller_inputs_torque(60, 0)
time.sleep(1)
otter.controller_inputs_torque(80, 0)
time.sleep(1)
otter.controller_inputs_torque(100, 0)
time.sleep(1)
otter.controller_inputs_torque(120, 0)
time.sleep(1)
otter.controller_inputs_torque(140, 0)
time.sleep(1)
otter.controller_inputs_torque(160, 0)
time.sleep(1)
otter.controller_inputs_torque(140, 0)
time.sleep(1)
otter.controller_inputs_torque(120, 10)
time.sleep(1)
otter.controller_inputs_torque(120, 20)
time.sleep(1)
otter.controller_inputs_torque(120, 30)
time.sleep(1)
otter.controller_inputs_torque(120, 35)
time.sleep(1)
otter.controller_inputs_torque(120, 35)
time.sleep(1)
otter.controller_inputs_torque(120, 35)
time.sleep(1)
otter.controller_inputs_torque(120, 20)
time.sleep(1)
otter.controller_inputs_torque(120, 0)
time.sleep(1)
otter.controller_inputs_torque(150, 0)
time.sleep(1)
otter.controller_inputs_torque(150, 0)
time.sleep(1)
otter.controller_inputs_torque(150, 0)
time.sleep(1)
otter.controller_inputs_torque(75, 20)
time.sleep(1)
otter.controller_inputs_torque(75, 40)
time.sleep(1)
otter.controller_inputs_torque(75, 60)
time.sleep(1)
otter.controller_inputs_torque(75, 80)
time.sleep(1)
otter.controller_inputs_torque(75, 75)
time.sleep(1)
otter.controller_inputs_torque(75, 75)
time.sleep(1)
otter.controller_inputs_torque(75, 75)
time.sleep(1)
otter.controller_inputs_torque(75, 75)
time.sleep(1)
otter.controller_inputs_torque(95, 60)
time.sleep(1)
otter.controller_inputs_torque(110, 40)
time.sleep(1)
otter.controller_inputs_torque(120, 20)
time.sleep(1)
otter.controller_inputs_torque(120, 0)
time.sleep(1)
otter.controller_inputs_torque(120, 0)
time.sleep(1)
otter.controller_inputs_torque(130, 0)
time.sleep(1)
otter.controller_inputs_torque(140, 0)
time.sleep(1)
otter.controller_inputs_torque(150, 0)
time.sleep(1)


